title: Github Pages tutorial
author: Pablo Nevares
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Whether you think you can, or you think you can't -- you're right.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
